import { createFileRoute } from "@tanstack/react-router";
import {
  Antenna,
  BatteryCharging,
  Brain,
  Cable,
  Cpu,
  Glasses,
  Radio,
  Terminal,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Panel } from "@/components/hud/Panel";

export const Route = createFileRoute("/_shell/hardware")({
  head: () => ({
    meta: [
      { title: "Hardware & SDR Integration Roadmap — Smart Helmet" },
      {
        name: "description",
        content:
          "Planned Smart Helmet hardware chain: broadband antenna, RTL-SDR, edge computer, HUD display and battery, plus the SDR signal pipeline.",
      },
      { property: "og:title", content: "Hardware Integration — Smart Helmet" },
      {
        property: "og:description",
        content: "Planned antenna → SDR → Python DSP → AI classifier → API → HUD architecture.",
      },
    ],
  }),
  component: Hardware,
});

const PIPELINE: { label: string; icon: LucideIcon; note: string }[] = [
  { label: "ANTENNA", icon: Antenna, note: "Broadband passive receive only" },
  { label: "SDR RECEIVER", icon: Radio, note: "RTL-SDR, 24 MHz – 1.7 GHz + 2.4 GHz downconvert" },
  { label: "PYTHON SIGNAL PROCESSING", icon: Terminal, note: "FFT, decimation, feature extraction" },
  { label: "AI CLASSIFIER", icon: Brain, note: "UAV RF signature model" },
  { label: "API / WEBSOCKET", icon: Cable, note: "/api/* + live push channel" },
  { label: "SMART HELMET DASHBOARD", icon: Glasses, note: "This application" },
];

const COMPONENTS = [
  {
    name: "RTL-SDR",
    icon: Radio,
    status: "SIMULATED / NOT CONNECTED",
    connection: "USB 2.0 → edge computer",
    description:
      "Low-cost software defined radio used purely as a passive receiver. Captures IQ samples of control and video downlink bands. No transmission, no jamming.",
  },
  {
    name: "BROADBAND ANTENNA",
    icon: Antenna,
    status: "SIMULATED / NOT CONNECTED",
    connection: "SMA coax → SDR input",
    description:
      "Omnidirectional wideband antenna covering common UAV bands (433/868 MHz, 915 MHz, 1.2 GHz, 2.4 GHz, 5.8 GHz). Bearing estimation needs a future antenna array.",
  },
  {
    name: "RASPBERRY PI / EDGE COMPUTER",
    icon: Cpu,
    status: "SIMULATED / NOT CONNECTED",
    connection: "Wi-Fi / USB-C to helmet HUD",
    description:
      "Runs the Python DSP chain and the AI classifier locally, then serves REST + WebSocket telemetry to the dashboard. Designed for offline field operation.",
  },
  {
    name: "HUD DISPLAY",
    icon: Glasses,
    status: "SIMULATED / NOT CONNECTED",
    connection: "HDMI / MIPI from edge computer",
    description:
      "Monocular helmet-mounted display rendering the tactical readout: threat state, confidence and signal strength at a glance.",
  },
  {
    name: "BATTERY",
    icon: BatteryCharging,
    status: "SIMULATED / NOT CONNECTED",
    connection: "Regulated 5V/12V rail",
    description:
      "Helmet-mounted Li-ion pack with power telemetry reported to the system page. Target endurance: one operational shift.",
  },
];

function Hardware() {
  return (
    <div className="space-y-4">
      <header>
        <h1 className="font-mono text-lg tracking-[0.16em]">HARDWARE</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Planned architecture for the sensor build. Nothing on this page is connected in the MVP —
          all telemetry shown in the app is generated by the simulation layer.
        </p>
      </header>

      <Panel title="Planned signal chain">
        <ol className="space-y-2">
          {PIPELINE.map(({ label, icon: Icon, note }, i) => (
            <li key={label}>
              <div className="flex items-center gap-3 rounded-sm border border-border bg-card px-3 py-2.5">
                <span className="label-hud w-6">{String(i + 1).padStart(2, "0")}</span>
                <Icon className="size-4 text-signal" aria-hidden />
                <span className="font-mono text-xs tracking-[0.12em]">{label}</span>
                <span className="ml-auto hidden text-xs text-muted-foreground sm:block">{note}</span>
              </div>
              {i < PIPELINE.length - 1 ? (
                <div className="ml-8 h-3 w-px bg-signal/50" aria-hidden />
              ) : null}
            </li>
          ))}
        </ol>
      </Panel>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {COMPONENTS.map(({ name, icon: Icon, status, connection, description }) => (
          <Panel key={name} title={name}>
            <div className="flex items-start gap-3">
              <Icon className="mt-0.5 size-5 text-idle" aria-hidden />
              <div className="space-y-2">
                <div>
                  <p className="label-hud">Status</p>
                  <p className="font-mono text-xs text-warn">{status}</p>
                </div>
                <div>
                  <p className="label-hud">Connection</p>
                  <p className="font-mono text-xs">{connection}</p>
                </div>
                <div>
                  <p className="label-hud">Description</p>
                  <p className="text-xs text-muted-foreground">{description}</p>
                </div>
              </div>
            </div>
          </Panel>
        ))}
      </div>

      <Panel title="Integration notes">
        <ul className="list-disc space-y-1.5 pl-5 text-xs text-muted-foreground">
          <li>The browser never talks to an SDR directly; all radio work happens on the edge computer.</li>
          <li>
            The edge computer will expose the same contract the UI already consumes:
            <span className="font-mono text-signal"> /api/status</span>,
            <span className="font-mono text-signal"> /api/detections</span>,
            <span className="font-mono text-signal"> /api/spectrum</span>,
            <span className="font-mono text-signal"> /api/system</span>.
          </li>
          <li>Real-time frames will arrive over WebSocket using the same frame shape as the simulator.</li>
          <li>The system is passive receive-only — it never transmits or interferes with any aircraft.</li>
        </ul>
      </Panel>
    </div>
  );
}
