/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDetectionsRouteImport } from './routes/_shell.detections'
import { Route as ShellHardwareRouteImport } from './routes/_shell.hardware'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSpectrumRouteImport } from './routes/_shell.spectrum'
import { Route as ShellSystemRouteImport } from './routes/_shell.system'
import { Route as ApiDetectionsRouteImport } from './routes/api/detections'
import { Route as ApiSpectrumRouteImport } from './routes/api/spectrum'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSystemRouteImport } from './routes/api/system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDetectionsRoute = ShellDetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHardwareRoute = ShellHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSpectrumRoute = ShellSpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemRoute = ShellSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ShellRoute,
} as any)
const ApiDetectionsRoute = ApiDetectionsRouteImport.update({
  id: '/api/detections',
  path: '/api/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpectrumRoute = ApiSpectrumRouteImport.update({
  id: '/api/spectrum',
  path: '/api/spectrum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemRoute = ApiSystemRouteImport.update({
  id: '/api/system',
  path: '/api/system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/detections': typeof ShellDetectionsRoute
  '/hardware': typeof ShellHardwareRoute
  '/settings': typeof ShellSettingsRoute
  '/spectrum': typeof ShellSpectrumRoute
  '/system': typeof ShellSystemRoute
  '/api/detections': typeof ApiDetectionsRoute
  '/api/spectrum': typeof ApiSpectrumRoute
  '/api/status': typeof ApiStatusRoute
  '/api/system': typeof ApiSystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/detections': typeof ShellDetectionsRoute
  '/hardware': typeof ShellHardwareRoute
  '/settings': typeof ShellSettingsRoute
  '/spectrum': typeof ShellSpectrumRoute
  '/system': typeof ShellSystemRoute
  '/api/detections': typeof ApiDetectionsRoute
  '/api/spectrum': typeof ApiSpectrumRoute
  '/api/status': typeof ApiStatusRoute
  '/api/system': typeof ApiSystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/detections': typeof ShellDetectionsRoute
  '/_shell/hardware': typeof ShellHardwareRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/spectrum': typeof ShellSpectrumRoute
  '/_shell/system': typeof ShellSystemRoute
  '/api/detections': typeof ApiDetectionsRoute
  '/api/spectrum': typeof ApiSpectrumRoute
  '/api/status': typeof ApiStatusRoute
  '/api/system': typeof ApiSystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/detections'
    | '/hardware'
    | '/settings'
    | '/spectrum'
    | '/system'
    | '/api/detections'
    | '/api/spectrum'
    | '/api/status'
    | '/api/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/detections'
    | '/hardware'
    | '/settings'
    | '/spectrum'
    | '/system'
    | '/api/detections'
    | '/api/spectrum'
    | '/api/status'
    | '/api/system'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/detections'
    | '/_shell/hardware'
    | '/_shell/settings'
    | '/_shell/spectrum'
    | '/_shell/system'
    | '/api/detections'
    | '/api/spectrum'
    | '/api/status'
    | '/api/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ApiDetectionsRoute: typeof ApiDetectionsRoute
  ApiSpectrumRoute: typeof ApiSpectrumRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSystemRoute: typeof ApiSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/detections': {
      id: '/_shell/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof ShellDetectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/hardware': {
      id: '/_shell/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof ShellHardwareRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/spectrum': {
      id: '/_shell/spectrum'
      path: '/spectrum'
      fullPath: '/spectrum'
      preLoaderRoute: typeof ShellSpectrumRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system': {
      id: '/_shell/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof ShellSystemRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/detections': {
      id: '/api/detections'
      path: '/api/detections'
      fullPath: '/api/detections'
      preLoaderRoute: typeof ApiDetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spectrum': {
      id: '/api/spectrum'
      path: '/api/spectrum'
      fullPath: '/api/spectrum'
      preLoaderRoute: typeof ApiSpectrumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system': {
      id: '/api/system'
      path: '/api/system'
      fullPath: '/api/system'
      preLoaderRoute: typeof ApiSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDetectionsRoute: typeof ShellDetectionsRoute
  ShellHardwareRoute: typeof ShellHardwareRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSpectrumRoute: typeof ShellSpectrumRoute
  ShellSystemRoute: typeof ShellSystemRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDetectionsRoute: ShellDetectionsRoute,
  ShellHardwareRoute: ShellHardwareRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSpectrumRoute: ShellSpectrumRoute,
  ShellSystemRoute: ShellSystemRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ApiDetectionsRoute: ApiDetectionsRoute,
  ApiSpectrumRoute: ApiSpectrumRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSystemRoute: ApiSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
